name: Build and Publish
on:
  push:
    branches:
      - master
jobs:
  shellLint:
    name: Shell Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      uses: actions/npm@master
      with:
        args: install
    - name: Publish
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.dtc_ci }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
